// FMAA Sections A & B — flashcard deck (derived from PRC e-books A.1–A.5, B.1–B.3)
// Each card: [section, front, back]. Sections: A1 A2 A3 A4 A5 B1 B2 B3
window.FMAA_CARDS = [
// ---------- A.1 ----------
["A1","ICMA (Institute of Certified Management Accountants) definition of accounting","Identifying, classifying, measuring, recording and communicating, in monetary terms, transactions/events of an economic entity that are of a financial character."],
["A1","Financial accounting: users and standards","External users (creditors, shareholders, investors, lenders, government). Follows GAAP (Generally Accepted Accounting Principles)/IFRS; standards change over time and differ by country; reports at end of each period; focuses on the past."],
["A1","Managerial accounting: users and standards","Internal decision makers (plan, evaluate, control, accountability for resources). No mandatory standards; similar across countries; stable over time; reports issued as management needs; past AND future focus."],
["A1","Which feature belongs to managerial accounting ONLY (vs. financial accounting)?","Reports are prepared based on management needs - not standards, not yearly, not past-only."],
["A1","Sole proprietorship: 3 key traits","One owner; not separate from owner for tax/legal; life limited to owner's life; unlimited liability."],
["A1","General partnership: key traits","Not a separate entity; easy to form (even without intent); all partners general; all have unlimited liability; life limited to partners; any change = new partnership."],
["A1","Limited partnership: key traits","Created by statute (LP (Limited Partnership) certificate filed); ≥1 general partner (unlimited liability, manages) + ≥1 limited partner (limited liability, cannot manage, name can't be in firm name; interest like a security)."],
["A1","LLP (Limited Liability Partnership): key traits","Statutory filing; usually professional services (legal, audit); all partners limited liability except personal malpractice; all may share management."],
["A1","Corporation: 8 characteristics","Separate legal entity; regulated by state/federal legislature; owned by shareholders; shareholders elect board; board appoints management; unlimited life; double taxation (corporate + dividends); limited liability."],
["A1","S-Corporation requirements","Not taxed at corporate level; must elect S status; ≤75 shareholders; only one class of stock."],
["A1","Joint venture (JV): definition","Partnership arrangement between two or more parties for a specified purpose/objective; ownership, costs, returns and risks shared."],
["A1","Limited Liability Company (LLC): key traits","Investors get limited liability and preferential tax treatment, subject to conditions/restrictions."],
["A1","Nonprofit organization","Public-benefit/social objectives; usually tax exempt; funded by grants/donations; may earn surplus but profit isn't primary; surplus reinvested."],
["A1","The accounting equation (with Dr/Cr)","Assets (Dr) = Liabilities (Cr) + Owner's Equity (Cr)"],
["A1","Definition of an asset","Probable future economic benefits obtained or controlled by an entity as a result of past transactions or events."],
["A1","Definition of a liability","Probable future sacrifices of economic benefits arising from present obligations to transfer assets or provide services in the future as a result of past transactions/events."],
["A1","Definition of equity","Residual interest in the assets of an entity after deducting liabilities = amounts invested by owners + retained earnings."],
["A1","Debit: definition","Entry that increases an asset or expense, or decreases a liability or equity; left side."],
["A1","Credit: definition","Entry that increases a liability or equity, or decreases an asset or expense; right side."],
["A1","Journal vs. Ledger vs. General ledger","Journal = book of original entry, chronological. Ledger = book of final entry (accounts). General ledger = primary record containing all accounts of the company."],
["A1","Cash basis vs. accrual basis","Cash: record revenue/expense when cash received/paid (tolerated for small firms). Accrual (GAAP (Generally Accepted Accounting Principles)/IFRS): revenue when earned, expense when incurred, regardless of cash."],
["A1","Customer pays $3,000 on Dec 4 for a TV delivered Jan 9: accrual treatment?","Dec 4 cash is an advance (liability, unearned revenue); revenue recognized Jan 9 on delivery."],
["A1","Conservatism (prudence)","Recognize expenses/liabilities as soon as possible under uncertainty; recognize revenues/assets only when assured. Rule of thumb: choose the solution least likely to overstate assets/income or understate liabilities/expenses."],
["A1","Consistency principle","Apply the same policies/procedures across periods; change only non-routinely when justified on a permanent basis."],
["A1","Matching principle","Recognize expenses in the same period as the related revenues (COGS (Cost of Goods Sold) when sold, depreciation over life, warranty and bad-debt estimates in year of sale)."],
["A1","Catalogues printed in Dec for a Jan promotion, paid in Jan: Dec 31 treatment and why?","Deferred cost (asset) at Dec 31 because of the MATCHING principle - they contribute to Jan revenues."],
["A1","Manufacturing labor cost is expensed when…","…the PRODUCT IS (Income Statement) SOLD (capitalized into inventory first) - matching principle."],
["A1","Accruals vs. Deferrals","Accruals: revenue earned/expense incurred before cash moves. Deferrals: cash paid/received before the revenue/expense belongs to the period (future periods)."],
["A1","Depreciation vs. amortization: what does each allocate?","Depreciation: allocating cost of TANGIBLE assets over periods benefited. Amortization: allocating costs to the periods in which they are consumed (intangibles)."],
// ---------- A.2 ----------
["A2","Double-entry bookkeeping rule","Every transaction has ≥2 entries; a change on one side of an account must be matched by an equal change on another side of a different account; total Dr = total Cr."],
["A2","Normal balance: assets, expenses, losses","Debit - increased by debits, decreased by credits."],
["A2","Normal balance: liabilities, equity, revenues, gains","Credit - increased by credits, decreased by debits."],
["A2","Contra-asset account","Valuation account that reduces an asset; credit balance shown in the assets section. e.g., Accumulated Depreciation, Allowance for Doubtful Debts."],
["A2","Contra-liability account","Valuation account that reduces a liability; debit balance shown in liabilities. e.g., Discount on Notes Payable."],
["A2","Adjunct account: definition and example","Valuation account that ADDS to an asset (debit) or liability (credit). e.g., Premium on Notes Payable."],
["A2","Accounting cycle: full order","Identify/measure → journalize → post → unadjusted trial balance → adjusting entries → adjusted TB → financial statements → closing entries → post-closing TB → (optional) reversing entries."],
["A2","Put these accounting-cycle steps in order: closing, reversing, posting, adjusting","Posting → Adjusting → Closing → Reversing."],
["A2","Elements of a journal entry","Date; ≥1 debit account; ≥1 credit account; equal debit and credit amounts; description."],
["A2","Trial balance: what it is and what it detects","NOT a financial statement; schedule of all GL (General Ledger) balances at a point in time; proves Dr = Cr; only detects errors where debits ≠ credits."],
["A2","Four types of adjusting entries","Accrued revenues (Dr Receivable/Cr Revenue); accrued expenses (Dr Expense/Cr Payable); prepaid expenses (Dr Expense/Cr Prepaid); unearned revenues (Dr Unearned Rev/Cr Revenue)."],
["A2","Closing entries: sequence","Revenues → Income Summary; expenses → Income Summary; Income Summary balance (net income) → Retained Earnings. Temporary accounts end at zero."],
["A2","Permanent (real) vs. temporary (nominal) accounts","Permanent: assets, liabilities, equity (incl. contra-assets like Allowance for Doubtful Accounts). Temporary: revenues, expenses, gains, losses, drawings/dividends, income summary."],
["A2","Post-closing trial balance contains…","Only permanent (real) accounts - nominal accounts have been closed."],
["A2","Reversing entries: timing and nature","Optional; made at the BEGINNING of the next period; exact opposite of the prior period's adjusting entries (accruals/deferrals) to simplify recording."],
["A2","Owner invests $60,000 cash: entry","Dr Cash 60,000 / Cr Capital 60,000"],
["A2","Pay 3 months' rent in advance, $3,000: entry","Dr Prepaid Rent 3,000 / Cr Cash 3,000"],
["A2","Receive $9,000 for services to be performed later: entry","Dr Cash 9,000 / Cr Unearned Revenue 9,000"],
["A2","Buy land $20,000: $7,000 cash + $13,000 note - entry","Dr Land 20,000 / Cr Cash 7,000, Cr Notes Payable 13,000"],
["A2","Send $2,000 invoice for services already provided: entry","Dr Accounts Receivable 2,000 / Cr Revenue 2,000"],
["A2","Month-end: one month of $3,000 prepaid rent used - adjusting entry","Dr Rent Expense 1,000 / Cr Prepaid Rent 1,000"],
["A2","Month-end: $200 of $800 supplies used - adjusting entry","Dr Supplies Expense 200 / Cr Supplies 200"],
["A2","Month-end: 1/3 of $9,000 unearned revenue earned - adjusting entry","Dr Unearned Revenue 3,000 / Cr Revenue 3,000"],
["A2","Entry: Dr Prepaid Property Taxes / Cr Property Tax Expense recognizes a(n)…","Prepaid (deferred) expense - unexpired cost."],
["A2","Effect of adjusting entry to accrue revenue from credit sales on A / L / OE (Owners' Equity)","Assets increase; liabilities no effect; owners' equity increases (Dr Receivable / Cr Revenue)."],
["A2","Which is a real (permanent) account: allowance for doubtful accounts, loss on retirement, interest expense, gain on retirement?","Allowance for doubtful accounts (contra-asset on the balance sheet)."],
// ---------- A.3 ----------
["A3","Definition of revenues","Inflows or enhancements of assets (or settlement of liabilities) during a period from delivering goods, rendering services, or other activities that constitute the entity's ONGOING MAJOR/CENTRAL operations."],
["A3","Definition of expenses","Outflows or using up of assets (or incurrence of liabilities) from delivering goods/rendering services in the entity's ongoing major/central operations."],
["A3","Gains vs. revenues: key differentiator","Gains/losses arise from PERIPHERAL or INCIDENTAL transactions; revenues/expenses from typical central activities. Laptop maker sells laptop = revenue; sells its machine above book value = gain."],
["A3","Four financial statements covered on the FMAA (Financial and Managerial Accounting Associate)","Balance sheet; income statement; statement of changes in equity; statement of cash flows. (OCI (Other Comprehensive Income)/comprehensive income/retained earnings statements out of scope.)"],
["A3","Primary external users of financial statements","Investors (assess risk/return of investment) and lenders/creditors (risk rating, ability to pay debts and interest)."],
["A3","Balance sheet: what it helps assess (5)","Operating capability/asset efficiency; capital structure, risk, creditworthiness; enterprise value; amounts/timing/uncertainty of future cash flows; liquidity and financial flexibility."],
["A3","Liquidity vs. financial flexibility","Liquidity: time expected until an asset is converted to cash. Financial flexibility: ability to alter amounts/timing of cash flows to respond to unexpected needs/opportunities."],
["A3","Balance sheet limitations (4)","Historical cost, not fair value; judgments and estimates; omits items not objectively recordable (human resources); snapshot at a point in time."],
["A3","The statement of financial position (balance sheet) is intended to help investors and creditors evaluate what?","Evaluate economic RESOURCES and OBLIGATIONS of a firm."],
["A3","Current assets: definition and order","Cash and assets expected to be converted to cash/sold/consumed within one year or the operating cycle, whichever is LONGER; listed by liquidity: cash, marketable securities, receivables, inventories, prepaids."],
["A3","Balance sheet asset categories (5)","Current assets; long-term investments; property, plant & equipment; intangible assets; other assets (deferred charges, non-current receivables, special funds, advances to subsidiaries)."],
["A3","Current liabilities: definition","Obligations expected to be liquidated through current assets or creation of other current liabilities within one year (or operating cycle, if longer): payables, collections in advance, current portion of LTD (Long-Term Debt)."],
["A3","When is a short-term obligation classified as long-term?","When the entity INTENDS and demonstrates ABILITY to refinance on a long-term basis (e.g., non-cancelable refinancing agreement maturing beyond one year)."],
["A3","Equity components on the balance sheet","Capital stock (par/stated value); additional paid-in capital; retained earnings (unappropriated/appropriated); accumulated other comprehensive income; less treasury stock."],
["A3","Authorized vs. issued vs. outstanding shares","Authorized: max the company may issue. Issued: shares sold to public. Outstanding: issued minus treasury shares."],
["A3","Subsequent events: two types and treatment","(1) Evidence about conditions existing at BS (Balance Sheet) date → ADJUST statements. (2) Conditions arising after BS date (stock issue/split, pending combination, litigation from post-BS event, fire/flood loss) → DISCLOSE only."],
["A3","Four supplemental information types on the balance sheet","Contingencies; valuations & accounting policies; contractual situations (covenants, leases, pensions, options); post-balance-sheet disclosures."],
["A3","Techniques of disclosure (4)","Parenthetical explanations; notes/footnotes; cross-reference and contra/adjunct items; supporting schedules."],
["A3","Income statement: usefulness (3)","Evaluate past performance; predict future cash flows and their risk; evaluate profitability and ability to generate sustainable earnings."],
["A3","Income statement limitations (3)","Numbers depend on accounting methods/estimates (quality of earnings); past period may not predict future; excludes items not reliably measurable (some unrealized gains → OCI (Other Comprehensive Income); brand, loyalty)."],
["A3","Which statement helps assess management's efficient and profitable use of resources?","The INCOME STATEMENT - not the statement of cash flows."],
["A3","Single-step vs. multiple-step income statement","Single-step: revenues − expenses. Multiple-step: separates operating from non-operating; matches costs with related revenues (gross profit, operating income, etc.)."],
["A3","Multiple-step income statement skeleton","Net sales − cost of sales = gross profit − selling & G&A (General and Administrative) = operating income ± other revenues/gains & expenses/losses = income before tax − tax = income from continuing ops ± discontinued ops (net of tax) = net income."],
["A3","Unusual and/or infrequent gains & losses: presentation","Reported before tax under Other Revenues & Gains / Other Expenses & Losses, after operating income; NOT net of tax; 'extraordinary items' no longer permitted."],
["A3","Discontinued operations: presentation and qualification","Disposal of a clearly distinguishable segment/product line; results + gain/loss on disposal shown NET OF TAX as a separate category after continuing operations."],
["A3","NOT a disposal of a segment (4 examples)","Disposing part of a line; relocating production/marketing; phasing out a product/service; changes due to technology."],
["A3","Employee inventory theft of $500,000: presentation","Classified as a LOSS and shown as a separate line item on the income statement."],
["A3","Change in accounting estimate: treatment","Prospective (period of change and future periods); never retroactive; not an error. Examples: useful life, salvage, collectability of receivables."],
["A3","Statement of changes in equity: structure","Beginning balance ± prior-period adjustment + net income + share issuances − dividends declared = ending balance, per equity component."],
["A3","Net income from equity changes: beg A 210k L 120k; investments 72k; withdrawals 75k; end A 270k L 171k","End equity 99k = beg 90k + 72k − 75k + NI (Net Income) → NI = $12,000."],
["A3","Statement of cash flows: purpose","Cash receipts/payments during a period classified as operating, investing, financing, plus net change in cash; evaluates liquidity, solvency, financial flexibility."],
["A3","Liquidity vs. solvency (cash flow context)","Liquidity: nearness to cash / settle current liabilities. Solvency: meet liabilities as they mature - operating cash flow is the most important factor."],
["A3","Cash flow statement limitations (3)","Excludes non-cash transactions; classification requires judgment; historical with limited predictive value."],
["A3","Operating activities: examples","Collections from customers; interest received; dividends received; payments to suppliers, employees, taxes; INTEREST PAID."],
["A3","Investing activities: examples","Buy/sell PP&E (Property, Plant and Equipment) and long-lived assets; make/collect loans to others (interest is operating); buy/sell other entities' equity/debt."],
["A3","Financing activities: examples","Issue stock / repurchase treasury stock; borrow / repay principal; PAY DIVIDENDS."],
["A3","Acquire asset $5,000 and borrow $10,000: CFS (Cash Flow Statement) classification","Investing outflow $5,000; financing inflow $10,000."],
["A3","Dividends paid 150k, interest paid 250k, equipment 350k: operating section total?","$250,000 (interest paid). Dividends = financing; equipment = investing."],
["A3","Purchase of treasury stock: CFS (Cash Flow Statement) classification","Financing activity."],
["A3","Credit-card interest incurred and paid: equity effect and CFS (Cash Flow Statement) class","Decreases owners' equity; operating outflow."],
["A3","Sources of information to prepare the CFS (3)","Comparative balance sheets; current income statement; selected transaction data."],
["A3","Direct vs. indirect method: which is on the FMAA (Financial and Managerial Accounting Associate)?","Only the INDIRECT method (start from net income and adjust)."],
["A3","Indirect method: non-cash expenses (depreciation, amortization, impairment)","ADD back to net income."],
["A3","Indirect method: gains/losses on sale of PP&E (Property, Plant and Equipment) or debt extinguishment","Subtract gains; add back losses (they belong to investing/financing)."],
["A3","Indirect method: changes in operating current assets","Increase → subtract; decrease → add."],
["A3","Indirect method: changes in operating current liabilities","Increase → add; decrease → subtract."],
["A3","Income before tax 60,000 incl. depreciation 5,000, bond discount amortization 6,000, interest 4,000: estimated cash flow?","60,000 + 5,000 + 6,000 = $71,000 (interest is cash; not added back)."],
["A3","Deriving depreciation expense when a machine was sold","Δ Accumulated depreciation + accumulated depreciation removed on disposal (cost − book value)."],
["A3","Deriving dividends paid from retained earnings","Dividends = Net income − Δ Retained earnings."],
["A3","Relationships among the statements (4)","NI (Net Income) reconciles retained earnings; CFS (Cash Flow Statement) explains change in BS (Balance Sheet) cash; BS equity ties to statement of changes in equity; depreciation on IS (Income Statement) accumulates on BS."],
// ---------- A.4 ----------
["A4","Corporate governance: definition and primary goal","System by which organizations are directed and controlled (rules, practices, processes balancing stakeholder interests). Goal: enhance long-term shareholder value while considering other stakeholders."],
["A4","Governance vs. risk management vs. control","Governance = broad framework; risk management (identify, assess, manage, control risks) and control (actions to manage risk) are components of good governance."],
["A4","Agency problem (principal-agent conflict)","Separation of ownership (shareholders = principals) and management (agents); managers may not act in shareholders' interest → board supervision/monitoring needed."],
["A4","Who is ultimately responsible for internal control? Who establishes/maintains it?","Board = ultimate responsibility. Senior management = establishes and maintains the system."],
["A4","COSO (Committee of Sponsoring Organizations of the Treadway Commission) definition of internal control","A process, effected by the board, management and other personnel, designed to provide reasonable assurance regarding: effectiveness/efficiency of operations; reliability of financial reporting; compliance with laws and regulations."],
["A4","What is the ultimate objective of managerial control?","To promote organizational effectiveness."],
["A4","Four risk responses","Tolerate/accept; treat (reduce likelihood/impact - internal controls); transfer; avoid."],
["A4","Inherent vs. managed vs. residual risk","Inherent (gross) = risk with no mitigation; managed = portion mitigated; residual (net) = what remains - profits are the reward for residual risk assumed."],
["A4","Inherent, control, detection risk (financial reporting)","Inherent: susceptibility to misstatement absent controls. Control: controls fail to prevent/detect/correct timely. Detection: assurance/audit procedures fail to detect."],
["A4","Risk that controls won't prevent/correct/detect errors timely = ?","Control risk."],
["A4","Reasonable vs. absolute assurance","Only reasonable assurance is possible: collusion, management override, and cost/benefit limits. Cost of controls must not exceed benefits."],
["A4","Benefits of strong internal control (3)","Better decisions from reliable info; better asset protection; lower external audit costs (reliance on controls)."],
["A4","Exposures of weak internal control (5)","Employee theft; loss of control over critical information; operational inefficiency; poor decisions; higher audit fees (substantive approach)."],
["A4","Centralized vs. decentralized structure: control implications","Centralized: standardized controls, easier to enforce. Decentralized: diverse operations, harder to implement uniform controls."],
["A4","Structure continuum: rigid vs. flat","Rigid/structured (army): least flexible, least risky, most control. Flat/free-rein: most flexible, riskiest, least control."],
["A4","Which management characteristic best indicates commitment to strong internal controls?","Funds allocated annually to update and improve information systems. (Negatives: small top group controls decisions; aggressive reporting; earnings-projection emphasis.)"],
["A4","Four duties to segregate","Authorization; recordkeeping; physical custody of the asset; periodic reconciliation of assets to records."],
["A4","Does segregation of duties guarantee no fraud?","No - collusion between two or more employees can defeat it."],
["A4","Sales-receivables cycle segregation examples","A/R (Accounts Receivable) adjuster ≠ payment poster; cash custodian ≠ write-off authorizer; deposit preparer ≠ bank reconciler."],
["A4","Purchases-payables segregation example and fraud prevented","PO (Purchase Order) issuer ≠ receiving recorder - prevents fictitious vendor/PO-box scheme."],
["A4","Cashier prepares a weekly deposit slip for all cash receipts: violation? Why?","Yes: custody + recording combined, and not timely (deposits should be intact and daily)."],
["A4","IS (Income Statement) environment: five roles to keep separate","Requirement/change request; authorization/approval; design/development; review/inspection/approval; implementation in production."],
["A4","Compensating controls (definition + 5 examples)","Controls reducing risk of an existing weakness when duties can't be separated: audit trails; reconciliation of applications; exception reports at supervisory level; transaction logs; supervisory review."],
["A4","Safeguarding assets: access rule","Access limited to authorized personnel - both direct physical access and indirect access via documents that authorize use/disposition."],
["A4","List controls that safeguard cash and payments","Cash registers; lockbox/direct deposit; intact daily deposits; treasury custody; pre-numbered forms; three-way match (PO (Purchase Order), invoice, receiving report) before payment; cancel vouchers."],
["A4","List controls that safeguard payroll","Payroll from supervisor-approved time cards; checks distributed by treasury (not supervisors); unclaimed checks held by an independent party."],
["A4","Physical access controls (list)","Locks (metal/electronic/biometric); deadman doors; alarms/motion detectors; cameras; guards; color-coded visitor badges; escorted visitors; single entry point; bonded personnel."],
["A4","Logical (software) controls (list)","Unique passwords; biometrics; secure PC (Personal Computer) storage; encryption; firewalls; anti-malware; backup and recovery."],
["A4","Reconciliation of recorded accountability with assets: who and how often?","Independent person (not the preparer); frequency depends on nature/amount of asset and cost - cash daily, inventory less often."],
// ---------- A.5 ----------
["A5","Working capital: definition and goal","Short-term assets (cash, marketable securities, receivables, inventories, short-term credits). Goal: minimize the operating cycle and the cash cycle."],
["A5","Operating cycle vs. cash cycle: definitions in words","Operating cycle = days to acquire, hold, sell, collect. Cash cycle = operating cycle − accounts payable payment days."],
["A5","Net working capital formula","Current assets − Current liabilities."],
["A5","Liquidity/return rule","More liquid assets → lower returns; shorter-term liabilities → less costly. Balance cost of liquidity vs. insolvency risk."],
["A5","Aggressive working-capital policy","Uses more current liabilities to finance longer-term assets; higher returns; risk of insufficient current assets → bankruptcy."],
["A5","Conservative working-capital policy","High current assets financed from longer-term liabilities; minimizes liquidity risk; lowest returns."],
["A5","Moderate / maturity-matching policy","Match maturity of assets with liabilities; balance current assets with current liabilities."],
["A5","What is the best financing tool for purchasing a new factory machine, and why?","Long-term sources - retained earnings or long-term loan (maturity matching)."],
["A5","Which decreases NWC (Net Working Capital): cash↓ & inventory↑; cash↓ & A/P (Accounts Payable)↓; cash↓ & fixed assets↑; cash↑ & LTD (Long-Term Debt)↑?","Cash↓ & fixed assets↑ (current assets fall, CL (Current Liabilities) unchanged). First two: no change; last: increase."],
["A5","Three motives for holding cash","Transaction; speculation; precautionary. (NOT 'to make a profit'.)"],
["A5","Factors affecting cash levels (5)","Revenue patterns/seasonality; operating expenses; contingencies; growth opportunities; market conditions."],
["A5","Cash forecast deficit vs. surplus: action","Deficit → arrange short-term financing in advance; surplus → invest a portion to generate income."],
["A5","Credit policy: components","Credit period; minimum credit standards; credit limits per customer/group; discount % and period. Set by top management, implemented by credit department."],
["A5","Default risk: definition (a.k.a. credit or bankruptcy risk)","(Credit/bankruptcy risk) borrower's inability to pay an obligation when due - must be weighed against added sales."],
["A5","Effect of extending the credit period","↑ sales & profit; ↑ A/R (Accounts Receivable) carried; ↑ default risk and opportunity cost of receivables."],
["A5","Effect of relaxing credit standards","↑ sales/profits; ↑ A/R (Accounts Receivable), bad debts, and collection costs. Tightening = opposite."],
["A5","Factoring: definition","Selling accounts receivable below face value to a factor."],
["A5","Factoring with recourse: sale treatment conditions (3)","Seller surrenders control of benefits; recourse obligation reasonably estimable; factor cannot force repurchase. Otherwise accounted for as a borrowing."],
["A5","Factoring without recourse: treatment and entry","Factor bears default risk (higher cost); treated as a sale: Dr Cash, Dr Loss on Sale of Receivables, Cr A/R (Accounts Receivable) at face."],
["A5","Types of inventory (4)","Raw materials (traceable); work-in-process; finished goods; materials & supplies (not traceable)."],
["A5","Reasons to carry inventory (5)","Supply/demand differences; cover process inefficiencies/delays; quantity discounts; level operations; avoid shortages/stockouts."],
["A5","Two inventory management questions","When to order (or manufacture)? How much to order (or manufacture)?"],
["A5","Ordering costs: what do they include?","Costs of preparing/placing a purchase order, including discounts lost from not ordering enough."],
["A5","Holding (carrying) costs","Storage; freight-in and insurance on shipment; facility depreciation/rent; insurance; property taxes; control/security; spoilage/theft/obsolescence; opportunity cost of capital."],
["A5","Which cost is often mistaken for an inventory carrying cost but is NOT one?","Shipping (freight-out) costs - related to sales, not carrying."],
["A5","Stockout costs and lead time","Costs of running out (lost goodwill, lost profits). Lead time = time from placing order to items received and ready for use."],
["A5","JIT (Just-In-Time): definition and objective","Inventory arrives just in time for use/sale; demand-driven; no warehousing; objective: minimize inventory and holding costs."],
["A5","JIT (Just-In-Time) effect on cost types (passing tip)","Increase in stockout costs; decrease in carrying costs."],
["A5","JIT (Just-In-Time) benefits and requirements","Less idle capital, storage, theft risk, control needs, property taxes; highlights material inefficiencies and supplier defects; needs reliable suppliers (small safety stock); often integrated with MRP (Materials Requirements Planning)."],
["A5","Materials Requirements Planning (MRP): what is it and what does it track?","Computer-based system converting the master production schedule into a detailed purchasing/production schedule; tracks levels, on-order quantities, lead times, usage rates."],
["A5","Accounts payable: why use it","Trade credit defers cash outlays; use only when cost of trade credit < other funding (depends on cash discount offered)."],
["A5","A/P (Accounts Payable) cycle: 10 steps","PO (legally binding) → validate goods received (receiving report) → vendor invoice → invoice validation/matching → approval → record liability → payment authorization → payment processing → documentation & reconciliation → payment confirmation."],
["A5","Benefits of effective A/P (Accounts Payable) management (7)","Access to trade credit; avoid overdue charges; easier invoice tracking; fraud prevention/detection; smoother cash flow; better supplier relationships; enhanced reporting."],
// ---------- B.1 ----------
["B1","Trade vs. nontrade receivables","Trade: from customers (A/R (Accounts Receivable) = oral promise; N/R (Notes Receivable) = written promise). Nontrade: peripheral (employee advances, dividends/interest receivable) - report separately."],
["B1","Terms 2/10, n/30 mean…","2% discount if paid within 10 days; otherwise gross amount due in 30 days."],
["B1","Gross method: entries for $5,000 sale, $2,000 paid within discount period","Dr A/R (Accounts Receivable) 5,000 / Cr Sales 5,000. Then Dr Cash 1,960, Dr Sales Discount 40 / Cr A/R 2,000. Sales Discount deducted from sales."],
["B1","Net method: treatment of forfeited discount","Record sale net (4,900). Late payment → Dr A/R (Accounts Receivable) 60 / Cr Sales Discount Forfeited 60 (Other Revenues), then collect gross."],
["B1","Valuation of short-term vs. noncurrent receivables","Short-term: net realizable value (amount expected to be collected). Noncurrent: present (discounted) value."],
["B1","Allowance method: basic entry","Dr Bad Debt Expense / Cr Allowance for Doubtful Debts (contra-asset)."],
["B1","Percentage of sales approach","Income-statement approach: expense = % × credit sales, ignoring existing allowance balance. (1% × $10M = $100,000.)"],
["B1","Percentage of receivables / aging approach","Balance-sheet approach: compute REQUIRED ending allowance (aging × % uncollectible); expense = required − existing balance. (56,100 − 12,500 = 43,600.)"],
["B1","Write-off of an uncollectible account: entry","Dr Allowance for Doubtful Debts / Cr Accounts Receivable (no income effect)."],
["B1","Recovery of a written-off account: entries","Reverse: Dr A/R (Accounts Receivable) / Cr Allowance. Collect: Dr Cash / Cr A/R."],
["B1","A/R (Accounts Receivable) and Allowance roll-forwards","A/R: Beg + credit sales − collections − write-offs = End. Allowance: Beg + bad debt expense + recoveries − write-offs = End."],
["B1","Collections 60% month of sale, 25% next, 15% second; sales Mar 280k, Apr 260k: May 1 A/R (Accounts Receivable)?","0.15×280,000 + 0.40×260,000 = $146,000."],
["B1","Which costs are inventory (product) costs that get capitalized?","Purchase cost; freight-in; insurance in transit; production costs (DM (Direct Materials), DL (Direct Labor), factory OH (Overhead)); sometimes procurement costs; interest on self-constructed/discrete-project assets."],
["B1","Which costs are period costs (never capitalized into inventory)?","Selling expenses; G&A (General and Administrative); freight-out; general interest costs."],
["B1","Periodic system COGS (Cost of Goods Sold) formula","Beginning inventory + Purchases − Purchase returns & allowances − Ending inventory (physical count)."],
["B1","Perpetual inventory system","Inventory records updated with each purchase/sale; annual physical count compared to records; differences investigated."],
["B1","Consigned goods belong in whose inventory?","The CONSIGNOR's, at cost including freight to the consignee."],
["B1","FOB (Free On Board) shipping point vs. FOB destination: goods in transit","Shipping point: title passes at carrier → buyer's inventory. Destination: title passes at buyer's dock → seller's inventory."],
["B1","FIFO (First-In, First-Out): characteristics","Oldest costs → COGS (Cost of Goods Sold); newest → ending inventory. Periodic = perpetual. Rising prices → lowest COGS, highest net income."],
["B1","LIFO (Last-In, First-Out): characteristics","Newest costs → COGS (Cost of Goods Sold); oldest remain. Periodic may ≠ perpetual. Rising prices → highest COGS, lowest net income."],
["B1","FIFO (First-In, First-Out) ending inventory: 11,500 units; beg 10,150 @ $6; bought 70,100 @ $7.50","All from purchases: 11,500 × 7.50 = $86,250."],
["B1","PP&E (Property, Plant and Equipment) cost includes…","Purchase price; property taxes/import duties; transportation-in; installation and trial runs; construction-period interest (expense after ready for use)."],
["B1","Depreciation: definition","Systematic and rational allocation of tangible-asset cost to the periods expected to benefit."],
["B1","Activity method formula","(Cost − Salvage) ÷ total capacity × usage. ($900,000/20,000 hrs = $45/hr × 3,000 = $135,000.)"],
["B1","Straight-line formula","(Cost − Salvage) ÷ useful life. ($900,000/5 = $180,000.)"],
["B1","Sum-of-years'-digits formula","(Cost − Salvage) × remaining life ÷ SYD (Sum-of-the-Years'-Digits), where SYD = n(n+1)/2. 5-yr: 5/15, 4/15, 3/15, 2/15, 1/15."],
["B1","Double-declining balance rules","Rate = 2 × SL (Straight-Line) rate; apply to BOOK VALUE (not cost − salvage); salvage ignored until book value would fall below it. $1M, 5 yrs: 400k, 240k, 144k, 86.4k, 29.6k."],
["B1","SYD (Sum-of-the-Years'-Digits): cost 250,000, salvage 50,000, 5 years - Year 3 expense and accumulated depreciation","Expense 200,000×3/15 = $40,000; accumulated 200,000×12/15 = $160,000."],
["B1","SL (Straight-Line) vs. declining balance: early years","DB (Declining Balance): higher depreciation, lower NI (Net Income), higher accumulated depreciation, lower retained earnings. Gross fixed assets same."],
["B1","Intangible assets: examples","Patents, copyrights, franchises, goodwill, trademarks, trade names, licenses, domain names, secret processes."],
["B1","Internally created intangibles: cost rule","Only direct costs (e.g., legal fees). R&D (Research and Development) is EXPENSED as incurred, never capitalized."],
["B1","Goodwill: recognition rule","Internally generated goodwill is never capitalized; only recognized through acquisition of another entity."],
["B1","Finite vs. indefinite-life intangibles","Finite: amortize (cost − residual) over useful life. Indefinite: no amortization; impairment test at least annually."],
["B1","Asset retirement: methods and rule","Sale, exchange, abandonment, involuntary conversion. Depreciate to retirement date; remove asset + accumulated depreciation; proceeds − book value = gain/loss shown below operating income."],
["B1","Cost 700,000; accumulated depreciation 495,000; gain 75,000: selling price?","Book value 205,000 + gain 75,000 = $280,000."],
["B1","When is a liability due within a year EXCLUDED from current liabilities?","(1) Settled from non-current assets (dedicated fund), or (2) both intention and demonstrated ability to refinance long-term (actual refinancing before issuance or non-cancelable agreement)."],
["B1","Unsecured bank loan types (3)","Promissory note; line of credit; revolving credit agreement (guaranteed line). Compensating balances raise the effective interest rate."],
["B1","Secured short-term loans: collateral forms","Pledged A/R (Accounts Receivable) or inventory (field warehousing; warehouse receipts); chattel mortgage (movable property); repurchase agreement."],
["B1","Commercial paper / bankers' acceptances","Commercial paper: short-term notes of major corporations. Bankers' acceptances: drafts drawn on bank deposits guaranteed by the bank at maturity."],
["B1","Revenue recognition: core principle","Recognize revenue to depict the transfer of promised goods/services to customers in an amount reflecting the consideration the entity expects to be entitled to."],
["B1","Revenue standard approach shift","'Asset-liability' approach replaces 'earned and realized' - revenue based on changes in assets and liabilities over the contract."],
["B1","Five-step revenue model","1 Identify contract; 2 Identify performance obligations; 3 Determine transaction price; 4 Allocate price to obligations; 5 Recognize when/as obligations satisfied."],
["B1","Valid contract criteria (5)","Approved and committed; rights identifiable; payment terms identifiable; commercial substance; collection probable."],
["B1","Cash received before performance obligation satisfied","Liability (unearned revenue) until control transfers; then Dr Unearned Revenue / Cr Sales Revenue, plus COGS (Cost of Goods Sold)."],
["B1","Performance obligation: 'distinct' test","Customer can benefit from the good/service separately AND the promise is separately identifiable (not interdependent/integrated). Software + separately sold support = 2 obligations; software + extensive customization = 1."],
["B1","Transaction price: four factors","Variable consideration; significant financing component; noncash consideration; consideration payable to the customer. Excludes third-party amounts (sales tax)."],
["B1","Variable consideration: two estimation methods","Expected value (probability-weighted; many outcomes). Most likely amount (single most likely; two outcomes)."],
["B1","Expected value: 50%×360k, 30%×320k, 20%×300k","180,000 + 96,000 + 60,000 = $336,000."],
["B1","Significant financing component: rule","If payment timing gives >1-year financing benefit, recognize revenue at cash-selling price; difference is interest revenue/expense. (13,310 due in 3 yrs, cash price 10,000 → interest 1,000/1,100/1,210 at 10%.)"],
["B1","Consideration payable to customer (rebates, coupons)","Reduces the transaction price unless it pays for a distinct good/service. Probable 5% rebate on $200,000 → revenue $190,000."],
["B1","Step 4 allocation basis","Relative standalone selling prices (estimate if unavailable). $300k contract; SSP 250k + 150k = 400k → license 187,500; support 112,500."],
["B1","Control: definition (Step 5)","Ability to direct the use of, and obtain the benefits from, the good/service, including preventing others from doing so."],
["B1","Over-time recognition criteria (any one)","Customer simultaneously receives/consumes benefits; entity creates/enhances a customer-controlled asset; no alternative use AND enforceable right to payment for performance to date."],
["B1","Output vs. input methods for measuring progress","Output: units delivered, milestones, appraisals. Input: costs incurred, labor/machine hours (cost-to-cost most common); straight-line if inputs even."],
["B1","Point-in-time control indicators (5)","Right to payment; legal title transferred; physical possession; customer has risks/rewards; customer acceptance."],
["B1","Warehouse contract with refundable deposit and payment only on completion: timing?","Point in time (no enforceable right to payment for work to date)."],
["B1","100,000 gallons sold at $3; 50,000 delivered by year-end; 75% cash received: Year 1 revenue?","50,000 × $3 = $150,000 (revenue follows delivery, not cash)."],
["B1","Annual lawn-service fee paid in advance: recognize revenue…","Over the year as services are performed (each visit is a distinct obligation)."],
["B1","Sales with right of return: recognize (3)","Revenue only for units expected to be kept; a refund liability (allowance for sales returns, contra-revenue); an asset for expected recovered inventory with COGS (Cost of Goods Sold) adjustment."],
["B1","Repurchase agreement: forward or call option - treatment","Repurchase price < original selling price → lease. ≥ original price → financing (borrowing)."],
["B1","Repurchase agreement: put option - treatment","No significant incentive to exercise → sale with right of return. Incentive & repurchase < original → lease. Repurchase ≥ original and > expected market value → financing."],
["B1","Bill-and-hold: extra criteria (4)","Substantive reason; product separately identified as customer's; ready for physical transfer; entity cannot use or redirect it."],
["B1","Principal vs. agent: revenue amount","Principal (controls good before transfer) → gross. Agent (arranges) → net commission only."],
["B1","Agent indicators (5)","Another party primarily responsible; no inventory risk; no pricing discretion; commission-based consideration; no credit risk."],
["B1","Consignment: when consignor recognizes revenue","Only after notification from the consignee that products were sold; consignee records commission revenue and payable to consignor."],
["B1","Consignment COGS (Cost of Goods Sold): 30,000 shipped + 1,500 freight; goods costing 10,000 sold","(10,000/30,000) × 31,500 = $10,500."],
["B1","Three expense recognition methods","Associating cause and effect (matching: COGS (Cost of Goods Sold), returns, bad debts, warranties); systematic and rational allocation (depreciation, prepaid insurance, interest/leases); immediate recognition (officers' salaries, G&A (General and Administrative), worthless patent)."],
["B1","Common stock issued: 1,000 shares $50 par at $75 - entry","Dr Cash 75,000 / Cr Common Stock 50,000 / Cr APIC (Additional Paid-In Capital) 25,000."],
["B1","Book value per common share","(Assets − Liabilities − Preferred stock) ÷ number of common shares."],
["B1","Pre-emptive right; value of a right (rights-on)","Right to buy new issues pro rata. Value = (share price rights-on − subscription price) ÷ (rights needed per share + 1)."],
["B1","Preferred stock: characteristics","Dividend preference; priority after debt, before common; usually no vote (may vote on mergers); dividends not guaranteed; may be convertible, callable, sinking fund, exchangeable, participating; par used for dividend %."],
["B1","Cumulative vs. noncumulative preferred","Cumulative: dividends in arrears (not a liability until declared) must be paid before common. Noncumulative: only current year's dividend."],
["B1","Treasury stock: nature and entry","Reacquired shares; issued but NOT outstanding (no vote, no dividends); Dr Treasury Stock / Cr Cash; contra-equity; reduces assets and equity; not an asset."],
["B1","Reasons to repurchase shares (3)","Improve EPS (Earnings Per Share)/ROE; support/increase share price; supply shares for employee compensation or stock dividends."],
["B1","Retained earnings: appropriated vs. free","Appropriated (restricted) by contract, board policy, or need - requires board authorization; free (unrestricted); total = sum of both."],
["B1","Prior-period adjustment: treatment and examples","Correction of prior-period errors; charged to OPENING retained earnings net of tax; excluded from current NI (Net Income). e.g., cash→accrual, unrecorded expense."],
["B1","Change in accounting principle: treatment","Cumulative effect, net of tax, adjusts BEGINNING retained earnings (retroactive computation). e.g., average cost → FIFO (First-In, First-Out); completed-contract → % completion."],
["B1","Change in depreciation method is treated as…","A change in ESTIMATE (prospective) - not a change in principle."],
["B1","Stock split: accounting","Memorandum entry only; no change to equity accounts. 4:1 split of $100 stock → ~$25. Reverse split consolidates shares."],
["B1","Cash dividends: entries","Declaration: Dr Retained Earnings / Cr Dividends Payable (liability arises at declaration). Payment: Dr Dividends Payable / Cr Cash."],
["B1","Small stock dividend (<20-25%)","Retained earnings reduced at FAIR MARKET VALUE; Cr Common Stock at par; Cr APIC (Additional Paid-In Capital) for excess."],
["B1","Large stock dividend (>20-25%)","Retained earnings reduced at PAR value; Cr Common Stock at par."],
["B1","5% stock dividend, 100,000 shares, $10 par, $18 market: RE (Retained Earnings) impact","Small dividend → 5,000 × $18 = $90,000 decrease."],
["B1","Cash dividend distributed + stock dividend declared: total equity change?","$0 - cash dividend left equity at declaration; stock dividend moves amounts within equity."],
["B1","Accumulated other comprehensive income","Gains/losses excluded from NI (Net Income); bypass IS (Income Statement) and retained earnings; permanent equity account, not closed."],
// ---------- B.2 ----------
["B2","Financial statement analysis: purpose and tools","Evaluate risk and performance; identify strengths/weaknesses. Tools: ratio analysis and trend analysis."],
["B2","Trend analysis: definition","Statement elements/ratios over successive periods to identify the pattern (amount and direction) of change and investigate causes."],
["B2","Common-size statements: definition and benefit","Each element expressed as a % of a base amount; allows comparison between companies of different sizes."],
["B2","Vertical common-size analysis: bases","Balance sheet base = TOTAL ASSETS; income statement base = NET SALES; each item as % of the same-year base."],
["B2","Horizontal common-size (common base year) analysis","Each item as a % of its BASE-YEAR amount → growth rates; also called variation/trend series analysis. 125% → 25% growth."],
["B2","'Advertising expense is 2% of sales' is an example of…","Vertical common-size analysis."],
["B2","Net income 120,000, sales 600,000: common-size %","20%."],
["B2","Growth rate formula","(Current ÷ Prior × 100) − 100. Salaries 622,310/568,920 → 9.38%."],
["B2","Largest % change: sales 6.0→6.6M, NI (Net Income) 500→540k, assets 10→10.5M, inventory 600→500k","Inventory: 83% of base → 17% change (sales 10%, NI 8%, assets 5%)."],
["B2","Future Tech case: warning signs","Inventories and receivables ballooning as % of assets; cash % collapsing; A/P (Accounts Payable) and overdrafts spiking; gross margin 25%→19%; G&A (General and Administrative) 3%→7% of sales; operating CF (Cash Flow) far below NI (Net Income)."],
// ---------- B.3 ----------
["B3","Four ratio groups on the FMAA (Financial and Managerial Accounting Associate)","Liquidity; leverage; activity; profitability."],
["B3","Current ratio: formula and interpretation","Current assets ÷ Current liabilities. Most common short-term solvency measure; very high may mean idle current assets."],
["B3","Quick (acid-test) ratio","(Current assets − Inventories − Prepayments) ÷ CL (Current Liabilities) = (Cash + Marketable securities + Receivables) ÷ CL. Better than current ratio because inventory excluded."],
["B3","Cash ratio: formula and what it measures","(Cash + Marketable securities) ÷ Current liabilities."],
["B3","Cash flow ratio: formula and what it measures","Cash flow from operations ÷ Average current liabilities."],
["B3","Net working capital ratio","Net working capital ÷ Total assets."],
["B3","CL (Current Liabilities) 2,000,000; NWC (Net Working Capital) 300,000; quick ratio 0.8: inventory?","CA (Current Assets) = 2,300,000; 0.8 = (2,300,000 − Inv)/2,000,000 → Inventory = $700,000."],
["B3","Capital structure and solvency","Capital structure = debt + equity mix. Solvency = ability to meet long-term liabilities as they mature."],
["B3","Financial leverage","Degree of debt in capital structure; interest is tax-deductible (dividends aren't); magnifies both gains and losses."],
["B3","Operating leverage","Effect of sales changes on operating income due to fixed vs. variable cost structure; high fixed costs → magnified swings."],
["B3","Total debt to total assets","Total debt (CL (Current Liabilities) + LTD (Long-Term Debt)) ÷ Total assets. Creditors prefer low; owners prefer higher; cyclical industries keep lower ratios."],
["B3","Debt/equity and long-term debt/equity","D/E (Debt-to-Equity) = Total debt ÷ Common equity (optimal minimizes WACC (Weighted Average Cost of Capital)). LTD (Long-Term Debt)/E = (Total debt − CL (Current Liabilities)) ÷ Common equity."],
["B3","Times interest earned","EBIT (Earnings Before Interest and Taxes) ÷ Interest expense. High TIE (Times Interest Earned) with high debt ratio preferred by lenders over low TIE with low debt. 20M/5M = 4."],
["B3","Inventory turnover and days sales in inventory","COGS (Cost of Goods Sold) ÷ Average inventory; Days = 360 ÷ turnover (= Avg inventory ÷ avg daily COGS)."],
["B3","A/R (Accounts Receivable) turnover and days sales outstanding","Net credit sales ÷ Average trade receivables; DSO (Days Sales Outstanding) = 360 ÷ turnover. High DSO = deteriorating liquidity; too low = credit too tight."],
["B3","A/R (Accounts Receivable) turnover: credit sales 3.6M; A/R 320k → 400k","3,600,000 ÷ 360,000 = 10."],
["B3","A/P (Accounts Payable) turnover and days purchases in payables","Net credit purchases ÷ Average A/P; Days = 360 ÷ turnover. Higher turnover = paying faster."],
["B3","Operating cycle: formula in days","Days sales in inventory + Days sales in receivables. Shorter is favorable."],
["B3","Cash conversion cycle: formula in days","Days in inventory + Days in receivables − Days purchases in payables (cash-to-cash)."],
["B3","Fixed assets turnover / total assets turnover","Sales ÷ Average fixed assets; Sales ÷ Average total assets."],
["B3","Unexpected decrease in which ratio may indicate fictitious inventory?","Total assets turnover (inventory inflates assets). Current ratio would rise; DSO (Days Sales Outstanding) and P/E (Price/Earnings) unaffected."],
["B3","Gross, operating, net profit margins","Gross profit ÷ Net sales; Operating income ÷ Net sales; Net income ÷ Net sales. OPM (Operating Profit Margin) falling vs. GPM (Gross Profit Margin) → poor control of other operating costs."],
["B3","Return on assets (ROA): formula and meaning","Net income ÷ Average total assets - earning power after all expenses, taxes, interest."],
["B3","Return on common equity and leverage signal","(Net income − Preferred dividends) ÷ Average common equity. ROE (Return on Equity) > ROA (Return on Assets) → leverage used effectively."],
["B3","Beechwood ROE (Return on Equity): NI (Net Income) 96,000; equity Jan 1 = 300k+12k+155k; Dec 31 = 300k+28k+206k","Avg equity 500,500 → 19.2% (include reserve for bond retirement; exclude bonds)."],
["A2","Three trial balances in the accounting cycle and what each proves","Unadjusted (after posting: Dr = Cr before adjustments); adjusted (after adjusting entries, used to prepare statements); post-closing (only permanent accounts carried forward)."],
["A2","General ledger vs. subsidiary ledger","General ledger = principal record of ALL accounts, consolidating subsidiary ledgers. Subsidiary ledger = record of increases/decreases in a single item (e.g., a customer's receivable)."],
["A3","Other external users of financial statements and what each needs","Government/regulators (taxes, compliance); unions (wage negotiation); financial advisors/rating agencies (advice); stock exchanges (listing/trading control); competitors, customers, public."],
["A3","Income statement footnote disclosures (4)","Detailed depreciation amounts; revenue recognition method; detailed tax amounts; earnings per share."],
["A3","Examples of unusual and/or infrequent gains and losses","Inventory/asset write-downs, restructuring charges; FX (Foreign Exchange) gains/losses; PP&E (Property, Plant and Equipment) disposal gains/losses; strike-related items; long-term contract accrual adjustments; natural disasters; government expropriation."],
["A3","Why is the direct method of operating cash flow rarely used?","Companies do not normally keep primary records of cash collections and cash payments by category, so the indirect method (net income adjusted) is used instead."],
["A3","CFS (Cash Flow Statement) classification of: interest received, dividends received, interest paid, dividends paid","Interest received = operating; dividends received = operating; interest paid = operating; dividends PAID = financing."],
["A3","Three things the statement of cash flows specifically helps users evaluate","Amount, timing and uncertainty of cash flows; ability to pay obligations as they come due; ability to generate future cash flows."],
["A4","Six factors that affect control risk","Control consciousness of people; adequacy of design (incl. segregation of duties); communication of control status; consistent application; frequency of independent checks; regular independent monitoring."],
["A5","Benefits of short-term financial forecasts for working capital (5)","Visibility of timing/amounts of cash inflows and outflows; better inventory and receivables management; ability to negotiate supplier terms and take early-payment discounts; less capital tied up; early identification of short-term financing needs."],
["A5","Accounts receivable are recorded net of which discount?","Trade discounts (cash/sales discounts are handled by the gross or net method)."],
["B1","Sales Discount (gross method) vs. Sales Discount Forfeited (net method): where on the income statement?","Sales Discount: deduction from sales to arrive at net sales. Sales Discount Forfeited: Other Revenues."],
["B1","Noncash consideration in a contract: how is the transaction price measured?","At the fair market value of what is received, measured at contract inception."],
["B1","Consignee's entry when consigned goods are sold for cash with a 10% commission","Dr Cash (sale price) / Cr Payable to Consignor (90%) / Cr Commission Revenue (10%). The consignee never records the goods as its inventory."],
["B1","Cost basis of an intangible acquired in exchange for other assets","Fair value of the consideration given or fair value of the intangible received, whichever is more reliable."],
["B1","Compensating balance: effect on a bank loan","Bank requires a minimum deposit balance; it raises the EFFECTIVE interest rate because part of the borrowed funds can't be used."],
["B1","Revolving credit agreement vs. line of credit","Line of credit: bank states the amount available on demand IF available. Revolving credit agreement: a GUARANTEED line - the amount is assured to be available."],
["B1","Interest on borrowings during construction of a self-constructed asset","May be capitalized as part of the asset's cost during construction; once the asset is ready for use, interest is expensed."],
["B3","How to read a change in operating profit margin relative to gross profit margin","Because COGS (Cost of Goods Sold) is in both, a falling operating margin while gross margin holds signals inefficient control of OTHER operating costs (selling, G&A (General and Administrative))."],
["B3","Which ratio do creditors rely on to judge ability to meet interest payments, and what tradeoff do lenders accept?","Times interest earned (EBIT (Earnings Before Interest and Taxes) ÷ interest). Lenders prefer a high TIE even with a high debt ratio over a low TIE with a low debt ratio."],
// ---------- Abbreviations ----------
["AB","LLP","Limited Liability Partnership"],
["AB","LLC","Limited Liability Company"],
["AB","LP","Limited Partnership"],
["AB","JV","Joint Venture"],
["AB","ICMA","Institute of Certified Management Accountants"],
["AB","FMAA","Financial and Managerial Accounting Associate"],
["AB","GAAP","Generally Accepted Accounting Principles"],
["AB","IFRS","International Financial Reporting Standards"],
["AB","A/R","Accounts Receivable"],
["AB","A/P","Accounts Payable"],
["AB","N/R","Notes Receivable"],
["AB","COGS","Cost of Goods Sold"],
["AB","NI","Net Income"],
["AB","CFS","Cash Flow Statement"],
["AB","BS","Balance Sheet"],
["AB","IS","Income Statement"],
["AB","TB","Trial Balance"],
["AB","GL","General Ledger"],
["AB","OE","Owners' Equity"],
["AB","CL","Current Liabilities"],
["AB","CA","Current Assets"],
["AB","LTD","Long-Term Debt"],
["AB","NWC","Net Working Capital"],
["AB","G&A","General and Administrative"],
["AB","PP&E","Property, Plant and Equipment"],
["AB","PO","Purchase Order"],
["AB","FIFO","First-In, First-Out"],
["AB","LIFO","Last-In, First-Out"],
["AB","SYD","Sum-of-the-Years'-Digits"],
["AB","SL","Straight-Line"],
["AB","DB","Declining Balance"],
["AB","EBIT","Earnings Before Interest and Taxes"],
["AB","TIE","Times Interest Earned"],
["AB","JIT","Just-In-Time"],
["AB","MRP","Materials Requirements Planning"],
["AB","DSO","Days Sales Outstanding"],
["AB","FOB","Free On Board"],
["AB","APIC","Additional Paid-In Capital"],
["AB","RE","Retained Earnings"],
["AB","ROA","Return on Assets"],
["AB","ROE","Return on Equity"],
["AB","OCI","Other Comprehensive Income"],
["AB","COSO","Committee of Sponsoring Organizations of the Treadway Commission"],
["AB","DM","Direct Materials"],
["AB","DL","Direct Labor"],
["AB","OH","Overhead"],
["AB","R&D","Research and Development"],
["AB","SSP","Standalone Selling Price"],
["AB","EPS","Earnings Per Share"],
["AB","WACC","Weighted Average Cost of Capital"],
["AB","D/E","Debt-to-Equity"],
["AB","P/E","Price/Earnings"],
["AB","OPM","Operating Profit Margin"],
["AB","GPM","Gross Profit Margin"],
["AB","IC","Internal Control"]
];

// Multiple-choice questions from the PRC session quizzes (choices index 0-3, ans = index)
window.FMAA_MCQ = [
["A1","Which is specific to managerial accounting only?",["It must follow a set of standards.","Its reports must be issued yearly.","It focuses on past performance.","Its reports are prepared based on management needs."],3,"Managerial reports are issued as management needs; financial accounting follows standards, is periodic, and is past-focused."],
["A1","An association of two or more businesses established for a special purpose and owned by two or more firms is a:",["Joint venture.","Wholly-owned subsidiary.","Special purpose entity.","Project financing arrangement."],0,"A JV is established by two or more parties for a special purpose; ownership, costs, returns and risks are shared."],
["A1","Conservatism (prudence) under uncertainty requires choosing the solution least likely to:",["Understate income.","Overstate liabilities.","Overstate assets.","Overstate expenses."],2,"Least likely to overstate assets/income or understate liabilities/expenses."],
["A1","Catalogues printed in Dec 2002 for a Jan 2003 promotion ($70,000, paid Jan) are a deferred cost at Dec 31, 2002 because of the:",["Matching principle.","Revenue recognition principle.","Objectivity principle.","Cost principle."],0,"Not yet used; they contribute to January revenues → expense in January (matching)."],
["A1","Under matching, labor of an employee who manufactures a product is charged to the income statement when the:",["Work is performed.","Employee is paid.","Product is completed.","Product is sold."],3,"Manufacturing labor is capitalized in inventory and expensed when sold."],
["A2","Correct order of accounting cycle steps:",["Posting, closing, adjusting, reversing.","Posting, adjusting, closing, reversing.","Posting, reversing, adjusting, closing.","Adjusting, posting, closing, reversing."],1,"Post → adjust → close → reverse (beginning of next period)."],
["A2","An entry debiting Prepaid Property Taxes and crediting Property Tax Expense recognizes a(n):",["Prepaid expense.","Accrued expense.","Prepaid revenue.","Expired cost."],0,"Reduces expense, increases prepaid - defers the expense (unexpired cost)."],
["A2","Effects of an adjusting entry to accrue revenue from credit sales (Assets / Liabilities / OE):",["Decrease / No effect / Decrease","Increase / No effect / Increase","No effect / Decrease / Increase","No effect / Increase / Decrease"],1,"Dr Receivable / Cr Revenue → assets and equity increase."],
["A2","Correct description of reversing entries:",["Mandatory step in the accounting cycle.","Made at the end of the next period after regular transactions.","Identical to the prior period's adjusting entries.","The exact opposite of the adjustments made in the previous period."],3,"Optional; at the beginning of the next period; exact opposite of adjustments."],
["A2","Which is a real (permanent) account?",["Allowance for doubtful accounts.","Loss on fixed asset retirement.","Interest expense.","Gain on fixed asset retirement."],0,"Contra-asset on the balance sheet; the others are temporary."],
["A3","The statement of cash flows should help assess all EXCEPT the:",["Amount, timing and uncertainty of prospective net cash inflows.","Company's ability to pay dividends and meet obligations.","Company's ability to generate future cash flow.","Management's efficient and profitable use of the firm's resources."],3,"That is the income statement's role."],
["A3","Deltech acquired a long-term productive asset for $5,000 and borrowed $10,000. Report as:",["Investing outflow $5,000; financing inflow $10,000.","Investing inflow $10,000; financing outflow $5,000.","Operating outflow $5,000; financing inflow $10,000.","Financing outflow $5,000; investing inflow $10,000."],0,"Asset purchase = investing outflow; borrowing = financing inflow."],
["A3","Dividends paid $150,000; interest paid $250,000; equipment purchased $350,000. Operating activities total:",["$150,000","$250,000","$350,000","$750,000"],1,"Only interest paid is operating; dividends = financing; equipment = investing."],
["A3","A statement of financial position is intended to help investors and creditors:",["Assess prospective net cash inflows.","Evaluate economic resources and obligations of a firm.","Evaluate economic performance.","Assess management's efficient use of resources."],1,"Resources and obligations = balance sheet."],
["A3","Income before taxes $60,000 includes depreciation $5,000, amortization of bond discount $6,000, interest expense $4,000. Estimated cash flow:",["$60,000","$66,000","$49,000","$71,000"],3,"Add back non-cash items: 60,000 + 5,000 + 6,000 = 71,000."],
["A3","Jan 1: assets $210,000, liabilities $120,000. Owner invested $72,000, withdrew $75,000. Dec 31: assets $270,000, liabilities $171,000. Net income:",["$0","$6,000","$9,000","$12,000"],3,"99,000 = 90,000 + 72,000 − 75,000 + NI → NI = 12,000."],
["A3","Which transaction is a financing activity?",["Purchase of equipment.","Purchase of treasury stock.","Sale of trademarks.","Payment of interest on a mortgage note."],1,"Treasury stock repurchase = financing; interest paid = operating."],
["A3","Credit card interest incurred and paid: effect on owners' equity / shown on CFS as:",["Decrease / Financing outflow","Decrease / Operating outflow","No effect / Financing outflow","No effect / Operating outflow"],1,"Interest expense reduces equity; interest paid is an operating outflow."],
["A3","Employees confessed to a $500,000 inventory theft with no restitution. Show as:",["A loss, separate line item in the income statement.","An accounts receivable, then written off.","Included in cost of goods sold.","Recorded directly to retained earnings."],0,"Material fraud loss is presented as a separate loss line."],
["A3","Which irregular item is a change in accounting estimate?",["Gains or losses from an expropriation.","Change from completed-contract to percentage-of-completion.","Gains or losses from foreign exchange rates.","A change in the collectability of receivables."],3,"Collectability is an estimate; completed-contract→POC is a change in principle."],
["A4","The ultimate objective of managerial control is to:",["Forestall management fraud.","Protect assets.","Promote organizational effectiveness.","Implement plans."],2,"Control increases the likelihood that objectives and goals are achieved."],
["A4","'Cost should not exceed benefits' and 'controls should not hinder efficiency' are recognized by:",["Limitations.","Management responsibility.","Methods of data processing.","Reasonable assurance."],3,"Only reasonable (not absolute) assurance can be obtained economically."],
["A4","Which is a violation of internal control?",["Mail clerk compares checks with source documents and forwards checks daily to the cashier with a listing.","Mail clerk forwards source documents daily to A/R for posting.","At week end the cashier prepares a deposit slip for all cash receipts received during the week.","GL clerk compares the cashier's summary entry with the A/R batch total."],2,"Custody and recording combined; deposits not intact/daily."],
["A4","Which best indicates management's commitment to strong internal controls?",["Decisions controlled by a small group of top executives.","Very aggressive attitudes toward financial reporting.","Funds allocated annually to update and improve information systems.","Strong emphasis on meeting earnings projections."],2,"Investment in systems strengthens the control environment; the others weaken it."],
["A4","The risk that controls will not prevent, correct, or detect errors in a timely manner is:",["Correction risk.","Detection risk.","Control risk.","Inherent risk."],2,"Definition of control risk."],
["A5","Which combined transaction decreases net working capital?",["$1M decrease in cash and $1M increase in inventory.","$1M decrease in cash and $1M decrease in accounts payable.","$1M decrease in cash and $1M increase in fixed assets.","$1M increase in cash and $1M increase in long-term debt."],2,"Current assets fall with no change in current liabilities."],
["A5","All are reasons for holding cash EXCEPT the:",["Precautionary motive.","Transaction motive.","Motive to make a profit.","Motive to meet future needs."],2,"Cash earns the lowest return; profit is not a motive."],
["A5","All are carrying costs of inventory EXCEPT:",["Storage costs.","Insurance.","Shipping costs.","Opportunity costs."],2,"Shipping (freight-out) relates to sales."],
["A5","Best financing tool for purchasing a new factory machine:",["Short-term loan.","Retained earnings.","Long-term loan.","Retained earnings or long-term loan."],3,"Maturity matching - long-term asset, long-term financing."],
["A5","Factoring refers to:",["Selling accounts receivable by one company to another.","Selling inventory to another company.","Converting overdue receivables to bad debt.","Adjusting inventories for obsolescence."],0,"Definition of factoring."],
["B1","Collections: 60% month of sale, 25% next month, 15% second month. Sales Jan 220k, Feb 200k, Mar 280k, Apr 260k. A/R on May 1:",["$107,120","$143,920","$146,000","$204,000"],2,"15% × 280,000 + 40% × 260,000 = 146,000."],
["B1","Beginning inventory 10,150 units ($60,900); purchased 70,100 units at $7.50. FIFO ending inventory of 11,500 units:",["$69,000","$71,025","$84,225","$86,250"],3,"All ending units come from purchases: 11,500 × 7.50."],
["B1","Vehicle cost $250,000, 5-year life, $50,000 salvage, SYD. End of year 3: depreciation expense / accumulated depreciation:",["$40,000 / $160,000","$50,000 / $200,000","$40,000 / $200,000","$50,000 / $160,000"],0,"Yr3 = 200,000×3/15 = 40,000; cumulative 12/15 = 160,000."],
["B1","Machine cost $700,000, accumulated depreciation $495,000, gain on sale $75,000. Selling price:",["$280,000","$205,000","$115,000","$240,000"],0,"Book value 205,000 + gain 75,000."],
["B1","$140,000 note refinanced long-term on Feb 1 and $200,000 note covered by a non-cancelable refinancing agreement (Feb 7) before the Mar 1 issuance date. Amount excludable from current liabilities at Dec 31:",["$0","$200,000","$140,000","$340,000"],3,"Both meet intent and ability to refinance."],
["B1","5% stock dividend on 100,000 shares, $10 par, market $18. Impact on retained earnings:",["Decrease $40,000.","Decrease $50,000.","Decrease $90,000.","No impact."],2,"Small dividend at fair value: 5,000 × 18."],
["B1","100,000 gallons sold at $3 on Oct 1; 50,000 delivered Dec 21 Year 1, rest Jan 8 Year 2; 50% paid Oct 1, 25% on each delivery. Revenue for Year 1:",["$75,000","$150,000","$225,000","$300,000"],1,"Revenue on delivery: 50,000 × $3."],
["B1","Lawn-care company charges $100/month; annual fee $1,050 paid in advance. Recognize revenue:",["When cash is collected.","Over the year as services are performed.","At the end of the contract year.","At the end of the fiscal year."],1,"Each visit is a distinct performance obligation satisfied over time."],
["B1","Dec 15: cash dividend of $120,000 distributed and 5% stock dividend declared (market value $100,000). Decrease in total shareholders' equity:",["$0","$100,000","$120,000","$220,000"],0,"Cash dividend reduced equity at declaration; stock dividend reclassifies within equity."],
["B2","When preparing a common-size balance sheet, the base amount is usually:",["Current assets.","Long-term assets.","Total assets.","Sales."],2,"Total assets = 100% on the balance sheet; sales on the income statement."],
["B2","An example of vertical common-size analysis is:",["Assessing stability of vertical integration.","Comparing ratios between firms in the same industry.","Advertising expense is 2% greater than the previous year.","Advertising expense for the current year is 2% of sales."],3,"Item as % of a same-year base."],
["B2","Sales $600,000; COGS $300,000; total assets $2,400,000; equity $1,500,000; net income $120,000. Net income on a common-size statement:",["5%","8%","20%","40%"],2,"120,000 ÷ 600,000."],
["B2","Prior/current: sales 6.0M/6.6M; NI 500k/540k; assets 10M/10.5M; inventory 600k/500k. Largest % change (horizontal):",["Sales revenue.","Net income.","Total assets.","Inventory."],3,"Inventory 83% → 17% change."],
["B2","Salaries $568,920 → $622,310. Annual growth rate in salaries:",["8.58%","9.38%","13.60%","18.03%"],1,"(622,310 ÷ 568,920) − 1."],
["B3","A/R end of Year 1 $320,000; credit sales Year 2 $3,600,000; A/R end of Year 2 $400,000. A/R turnover:",["0.10","9.00","10.00","11.25"],2,"3,600,000 ÷ 360,000."],
["B3","Beechwood: net income $96,000; equity Jan 1 = common 300,000 + reserve 12,000 + RE 155,000; Dec 31 = 300,000 + 28,000 + 206,000. Return on shareholders' equity:",["19.2%","19.9%","32.0%","39.5%"],0,"96,000 ÷ average equity 500,500."],
["B3","An unexpected decrease in which ratio could indicate fictitious inventory?",["Days sales outstanding.","Total assets turnover ratio.","Price/earnings ratio.","Current ratio."],1,"Inflated inventory raises assets → lower sales/assets."],
["B3","Current liabilities $2,000,000; net working capital $300,000; quick ratio 0.8. Inventory:",["$240,000","$700,000","$1,360,000","$1,600,000"],1,"CA 2.3M; (2.3M − Inv)/2M = 0.8."],
["B3","Interest expense $5M; sales $50M; EBIT $20M; net income $8M. Times interest earned:",["10","4","1.6","0.25"],1,"EBIT ÷ interest = 20/5."]
];
